name: Auto Refresh SAM.gov

on:
  workflow_dispatch: {}
  schedule:
    # Reduced frequency: every 2 hours instead of every hour to conserve quota
    - cron: '0 */2 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SAM_KEYS:        ${{ secrets.SAM_KEYS }}
      PYTHONPATH:      ${{ github.workspace }}
      TZ:              America/Denver
      # Quota-conscious settings
      DAYS_BACK:       '1'           # Only look at last 1 day
      PAGE_SIZE:       '200'         # Reasonable page size
      MAX_RECORDS:     '2000'        # Lower max to conserve quota

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install sqlalchemy sqlmodel pandas numpy requests pytz
          fi

      - name: Run auto refresh (quota-conscious)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS:        ${{ secrets.SAM_KEYS }}
          DAYS_BACK:       '1'
          PAGE_SIZE:       '200'
          MAX_RECORDS:     '2000'
          PYTHONUNBUFFERED: '1'
        run: |
          set -euo pipefail
          echo "=== Auto refresh start ==="
          date
          # Remove timeout and let the script handle quota limits gracefully
          python -u scripts/auto_refresh.py
          echo "=== Auto refresh done ==="

      - name: Run backfill descriptions (reduced scope)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS:        ${{ secrets.SAM_KEYS }}
          BACKFILL_MAX:    '100'        # Reduced from default 500
          BACKFILL_DELAY_SEC: '1.0'     # Slower to be more polite
        run: python -u scripts/backfill_descriptions.py