name: Auto refresh SAM.gov feed

on:
  schedule:
    # 3am MT
    - cron: '0 9 * * *'   # MDT (UTC-6)
    - cron: '0 10 * * *'  # MST (UTC-7)
    # 12pm (noon) MT
    - cron: '0 18 * * *'  # MDT
    - cron: '0 19 * * *'  # MST
    # 7pm MT  (next-day UTC for MDT/MST)
    - cron: '0 1 * * *'   # MDT
    - cron: '0 2 * * *'   # MST
  workflow_dispatch: {}

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SAM_KEYS: ${{ secrets.SAM_KEYS }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run auto refresh
        working-directory: ${{ github.workspace }}
        run: |
          python scripts/auto_refresh.py