name: Auto Refresh SAM.gov

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run regardless of local hour'
        type: boolean
        default: false
  schedule:
    # Run every hour; your script will skip unless it's 3/12/19 MT (or forced)
    - cron: '0 * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SAM_KEYS:        ${{ secrets.SAM_KEYS }}
      PYTHONPATH:      ${{ github.workspace }}
      TZ:              America/Denver

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install sqlalchemy sqlmodel pandas numpy requests pytz
          fi

      - name: Preflight & run auto refresh (verbose)
        env:
          # Pass the checkbox straight through as "true"/"false";
          # your script normalizes FORCE_RUN internally.
          FORCE_RUN:       ${{ github.event.inputs.force_run }}
          DAYS_BACK:       '1'
          PYTHONUNBUFFERED: '1'
        run: |
          set -euo pipefail
          echo "=== Preflight ==="
          date
          echo "FORCE_RUN=${FORCE_RUN}"
          echo "DAYS_BACK=${DAYS_BACK}"
          echo "PWD=$(pwd)"
          ls -la
          echo "Python:"
          python -V
          echo "Path check:"
          python -c "import sys,os; print('sys.path0=',sys.path[0]); print('has scripts/auto_refresh.py=', os.path.exists('scripts/auto_refresh.py')); print('has get_relevant_solicitations.py=', os.path.exists('get_relevant_solicitations.py'))"
          echo "=== Running script (12m timeout) ==="
          timeout 12m python -u scripts/auto_refresh.py
          echo "=== Script finished ==="