name: Auto Refresh SAM.gov

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force run regardless of local hour'
        type: boolean
        default: false
  schedule:
    - cron: '0 * * * *'   # runs hourly; script will skip except 3/12/19 MT unless forced

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SAM_KEYS:        ${{ secrets.SAM_KEYS }}
      PYTHONPATH:      ${{ github.workspace }}
      TZ:              America/Denver

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install sqlalchemy sqlmodel pandas numpy requests pytz
          fi

      - name: Run auto refresh
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS:        ${{ secrets.SAM_KEYS }}
          # 👇 Pass FORCE_RUN based on the checkbox in "Run workflow"
          FORCE_RUN:       ${{ github.event.inputs.force && '1' || '' }}
        run: python scripts/auto_refresh.py