name: Auto Refresh SAM.gov

on:
  workflow_dispatch: {}
  schedule:
    # Run every hour; auto_refresh pulls metadata only, backfill fills in missing descriptions
    - cron: '0 * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SAM_KEYS:        ${{ secrets.SAM_KEYS }}
      PYTHONPATH:      ${{ github.workspace }}
      TZ:              America/Denver

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install sqlalchemy sqlmodel pandas numpy requests pytz
          fi

      - name: Run auto refresh (hourly, fast)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS:        ${{ secrets.SAM_KEYS }}
          DAYS_BACK:       '1'
          PYTHONUNBUFFERED: '1'
        run: |
          set -euo pipefail
          echo "=== Auto refresh start ==="
          date
          timeout 12m python -u scripts/auto_refresh.py
          echo "=== Auto refresh done ==="

      - name: Run backfill descriptions
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS:        ${{ secrets.SAM_KEYS }}
        run: python -u scripts/backfill_descriptions.py