name: Auto Refresh SAM.gov

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run regardless of local hour'
        type: boolean
        default: false
  schedule:
    - cron: '0 * * * *'   # runs hourly; script will skip except 3/12/19 MT unless forced

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SAM_KEYS:        ${{ secrets.SAM_KEYS }}
      PYTHONPATH:      ${{ github.workspace }}
      TZ:              America/Denver

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install sqlalchemy sqlmodel pandas numpy requests pytz
          fi

      - name: Run auto refresh
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS:        ${{ secrets.SAM_KEYS }}
          FORCE_RUN:       ${{ github.event.inputs.force_run == 'true' && '1' || '' }}
          DAYS_BACK:       1
          PYTHONUNBUFFERED: '1'
          TZ: America/Denver
        run: 
          set -xeuo pipefail
          date
          echo "FORCE_RUN=${FORCE_RUN}"
          echo "DAYS_BACK=${DAYS_BACK}"
          python -u -c "print('preflight ok', flush=True)"
          timeout 12m python -u scripts/auto_refresh.py