name: Auto Refresh SAM Feed

on:
  push:
    branches: [ main ]   # lets you see a run right after you push
  workflow_dispatch:      # lets you trigger manually
  schedule:
    - cron: "0 * * * *"   # runner wakes hourly; script checks your local-time windows

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt || true
          pip install sqlalchemy sqlmodel pandas psycopg2-binary

      - name: Run scheduled refresh
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS: ${{ secrets.SAM_KEYS }}
          MAX_RESULTS_REFRESH: "500"
          LOCAL_TZ: "America/New_York"   # change to your local TZ
        run: |
          python scripts/auto_refresh.py