name: Auto Refresh SAM Feed

on:
  workflow_dispatch:      # allow manual trigger
  schedule:
    - cron: "0 * * * *"   # run hourly; script checks whether it's 3a/12p/7p MT

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt || true
          pip install sqlalchemy sqlmodel pandas psycopg2-binary

      - name: Run auto refresh
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SAM_KEYS: ${{ secrets.SAM_KEYS }}
          MAX_RESULTS_REFRESH: "500"
          LOCAL_TZ: "America/Denver"   # mountain time zone
        run: |
          python scripts/auto_refresh.py